route:
  group_by: [cluster, alertname]
  receiver: PagerDuty
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
  - receiver: 'DeadManSnitch'
    group_wait: 10s
    repeat_interval: 5m
    match:
      alertname: PrometheusAlertmanagerE2eDeadManSwitch

receivers:
- name: PagerDuty
  pagerduty_configs:
  - routing_key: __RoutingKey__
    severity: '{{ if .Labels.severity }}{{ .Labels.severity | toLower }}{{ else }}critical{{ end }}'

- name: DeadManSnitch
  webhook_configs:
  - url: __SnitchUrl__