route:
 group_by: [cluster, alertname, service]
 receiver: PagerDuty-Global-Event-Rules
 group_wait: 30s
 group_interval: 5m
 repeat_interval: 3h

receivers:
- name: PagerDuty-Global-Event-Rules
  pagerduty_configs:
  - service_key: __PagerDutyServiceKey__