global:
  scrape_interval: 5s 
  
  external_labels:
    monitor: 'hetzner-monitor'

rule_files:
  - 'prometheus_alerts.yml'
  - 'node_exporter_alerts.yml'

scrape_configs:  
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - localhost:9090

  - job_name: 'node'    
    scheme: https
    tls_config:
      ca_file: node_exporter.crt
    basic_auth:
      username: prometheus
      password: passwd
    static_configs:
      - targets:
        - host.docker.internal:9100         

  - job_name: 'docker'
    static_configs:
      - targets:
          - host.docker.internal:9323

alerting:
  alertmanagers:
    - timeout: 10s
      api_version: v2
      path_prefix: /
      scheme: http
      follow_redirects: true
      static_configs:
        - targets:
            - "alertmanager:9093"  