version: '3.8'
services:
  prometheus:
    image: prom/prometheus:v2.36.2
    restart: always
    ports:
      - 9091:9090      
    volumes:
      - ./prometheus:/etc/prometheus
      - /etc/node_exporter/node_exporter.crt:/etc/prometheus/node_exporter.crt
      - prometheus:/prometheus
    depends_on:
      - alertmanager
    extra_hosts:
      - "host.docker.internal:host-gateway"      
    networks:
      - monitoring
  
  alertmanager:
    image: prom/alertmanager:v0.24.0
    restart: always
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager:/config
      - alertmanager_data:/data
    command: --config.file=/config/alertmanager.yml --web.external-url=http://example.com:9093
    networks:
      - monitoring
    
  grafana: 
    image: grafana/grafana-oss:9.0.2
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitoring

volumes:
  prometheus:
  grafana_data:
  alertmanager_data:

networks:
  monitoring:
    driver: bridge